2025-06-28 09:07:03 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 09:07:03 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 09:07:03 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:07:05 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:07:05 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:07:31 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 09:07:31 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:07:33 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:07:33 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:07:53 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 09:07:53 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:07:55 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:07:55 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:08:59 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:08:59] "OPTIONS /api/user/register HTTP/1.1" 200 -
2025-06-28 09:08:59 - root - INFO - user_controller:144 - 111111111111: admin
2025-06-28 09:08:59 - root - INFO - user_controller:149 - √‹¬Îº”√‹≥…π¶
2025-06-28 09:08:59 - root - INFO - user_service:14 - user_service use rgister
2025-06-28 09:08:59 - dao.user_dao - INFO - user_dao:30 - make new user: admin
2025-06-28 09:08:59 - dao.user_dao - INFO - user_dao:39 -  user 1
2025-06-28 09:08:59 - dao.user_dao - INFO - user_dao:50 - new user has been created,waiting for writing
2025-06-28 09:08:59 - dao.user_dao - INFO - user_dao:54 - ”√ªß¥¥Ω®≥…π¶: ID=1, ”√ªß√˚=admin, ” œ‰=2074437070@qq.com
2025-06-28 09:08:59 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:08:59] "[35m[1mPOST /api/user/register HTTP/1.1[0m" 201 -
2025-06-28 09:09:14 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:09:14] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:09:14 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:09:14 - root - INFO - user_controller:242 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:09:14 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:09:14 - app - ERROR - user_controller:295 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 250, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 49, in login
    if not self.user_dao.verify_password(password, user.password):
                                                   ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'password'
2025-06-28 09:09:14 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:09:14] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 09:11:28 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 09:11:28 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:11:30 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:11:30 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:11:45 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:11:45] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:11:45 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:11:45 - root - INFO - user_controller:242 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:11:45 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:11:45 - root - INFO - user_service:59 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:11:45 - app - ERROR - user_controller:295 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 250, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 66, in login
    'role': user.role  # »∑±£”√ªßƒ£–Õ”–role◊÷∂Œ
            ^^^^^^^^^
AttributeError: 'User' object has no attribute 'role'
2025-06-28 09:11:45 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:11:45] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 09:14:26 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 09:14:26 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:14:28 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:14:28 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:14:55 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:14:55] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:14:55 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:14:55 - root - INFO - user_controller:242 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:14:55 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:14:56 - root - INFO - user_service:59 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:14:56 - root - INFO - user_controller:251 - —È÷§√‹¬Îing
2025-06-28 09:14:56 - app - ERROR - user_controller:295 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 267, in login
    'role': user['role'],
            ~~~~^^^^^^^^
KeyError: 'role'
2025-06-28 09:14:56 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:14:56] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 09:17:00 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 09:17:00 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:17:02 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:17:02 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:17:44 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:17:44] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:17:44 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:17:44 - root - INFO - user_controller:242 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:17:44 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:17:44 - root - INFO - user_service:59 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:17:44 - root - INFO - user_controller:251 - —È÷§√‹¬Îing
2025-06-28 09:17:44 - app - ERROR - user_controller:295 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 267, in login
    'role': user['role'],
            ~~~~^^^^^^^^
KeyError: 'role'
2025-06-28 09:17:44 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:17:44] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 09:19:47 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\controller\\user_controller.py', reloading
2025-06-28 09:19:47 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:19:48 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:19:48 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:20:04 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:20:04] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:20:04 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:20:04 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:20:04 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:20:04 - root - INFO - user_service:59 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:20:04 - root - INFO - user_controller:250 - —È÷§√‹¬Îing
2025-06-28 09:20:04 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:20:04] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 09:23:03 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:23:03] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:23:03 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:23:03 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:23:03 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:23:03 - root - INFO - user_service:59 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:23:03 - root - INFO - user_controller:250 - —È÷§√‹¬Îing
2025-06-28 09:23:03 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:23:03] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 09:24:42 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:24:42] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:24:42 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:24:42 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:24:42 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:24:42 - root - INFO - user_service:59 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:24:42 - root - INFO - user_controller:250 - —È÷§√‹¬Îing
2025-06-28 09:24:42 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:24:42] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 09:34:44 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 09:34:44 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:34:46 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:34:46 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:34:49 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\controller\\user_controller.py', reloading
2025-06-28 09:34:49 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:34:51 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:34:51 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:35:14 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:35:14] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:35:14 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:35:14 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:35:14 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:35:14 - root - INFO - user_service:61 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:35:14 - root - INFO - user_controller:250 - —È÷§√‹¬Îing
2025-06-28 09:35:14 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:35:14] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 09:36:00 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:36:00] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:36:01 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:36:01 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:36:01 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:36:01 - root - INFO - user_service:61 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:36:01 - root - INFO - user_controller:250 - —È÷§√‹¬Îing
2025-06-28 09:36:01 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:36:01] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 09:37:38 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 09:37:38 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:37:40 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:37:40 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:38:15 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 09:38:16 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:38:17 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:38:17 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:38:44 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:38:44] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:38:44 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:38:44 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:38:44 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:38:44 - root - INFO - user_service:40 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 01:38:44.550076+00:00
2025-06-28 09:38:44 - root - INFO - user_service:61 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 09:38:44 - root - INFO - user_controller:250 - —È÷§√‹¬Îing
2025-06-28 09:38:44 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:38:44] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 09:50:44 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 09:50:44 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:50:46 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:50:46 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:50:58 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\dao\\user_dao.py', reloading
2025-06-28 09:50:58 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 09:51:00 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 09:51:00 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 09:51:23 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:51:23] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:51:23 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:51:23 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:51:23 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:51:23 - app - ERROR - user_controller:293 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 249, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user.user_dao.update_user_info(email)
    ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'user_dao'
2025-06-28 09:51:23 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:51:23] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 09:58:02 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:58:02] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 09:58:02 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 09:58:02 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 09:58:02 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 09:58:02 - app - ERROR - user_controller:293 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 249, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user.user_dao.update_user_info(email)
    ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'user_dao'
2025-06-28 09:58:02 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 09:58:02] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 10:00:07 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 10:00:07 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 10:00:09 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 10:00:09 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 10:00:14 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 10:00:14] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 10:00:14 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 10:00:14 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 10:00:14 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 10:00:14 - app - ERROR - user_controller:293 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 249, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user.user_dao.update_user_info(email)
    ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'user_dao'
2025-06-28 10:00:14 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 10:00:14] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 10:06:42 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 10:06:42 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 10:06:44 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 10:06:44 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 10:06:54 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 10:06:54] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 10:06:54 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 10:06:54 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 10:06:54 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 10:06:54 - root - INFO - user_service:42 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 02:06:55
2025-06-28 10:06:54 - root - INFO - user_service:63 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 10:06:54 - root - INFO - user_controller:250 - —È÷§√‹¬Îing
2025-06-28 10:06:54 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 10:06:54] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 11:32:16 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 11:32:16 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 11:32:16 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 11:32:17 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 11:32:17 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 11:33:02 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 11:33:02] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 11:33:03 - root - INFO - user_controller:240 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 11:33:03 - root - INFO - user_controller:241 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 11:33:03 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 11:33:03 - root - INFO - user_service:42 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 03:33:03
2025-06-28 11:33:03 - root - INFO - user_service:63 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 11:33:03 - root - INFO - user_controller:250 - —È÷§√‹¬Îing
2025-06-28 11:33:03 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 11:33:03] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 11:43:17 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\dao\\user_dao.py', reloading
2025-06-28 11:43:17 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 11:43:18 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 11:43:18 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 11:43:46 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\dao\\user_dao.py', reloading
2025-06-28 11:43:46 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 11:43:47 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 11:43:47 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 11:44:54 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\controller\\user_controller.py', reloading
2025-06-28 11:44:54 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 11:55:02 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 11:55:02 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 11:55:02 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 11:55:03 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 11:55:03 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:03:07 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 14:03:07 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:03:10 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:03:10 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:03:11 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:03:12 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:03:13 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:03:13 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:12:04 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\dao\\operation_dao.py', reloading
2025-06-28 14:12:05 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:12:06 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:12:06 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:18:35 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\controller\\user_controller.py', reloading
2025-06-28 14:18:35 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:18:58 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 14:18:58 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 14:18:58 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:18:59 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:18:59 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:19:21 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:19:21] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:19:21 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:19:21 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:19:21 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:19:21 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1656, in do_init
    self._setup_entity()
    ~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1866, in _setup_entity
    self._clsregistry_resolve_name(argument)(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 516, in _resolve_name
    rval = d[token]
           ~^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\util\_collections.py", line 345, in __missing__
    self[key] = val = self.creator(key)
                      ~~~~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 463, in _access_cls
    return _determine_container(key, decl_class_registry[key])
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 409, in _determine_container
    value = value.attempt_get([], key)
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 219, in attempt_get
    raise exc.InvalidRequestError(
    ...<4 lines>...
    )
sqlalchemy.exc.InvalidRequestError: Multiple classes found for path "User" in the registry of this declarative base. Please use a fully module-qualified path.
2025-06-28 14:19:21 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:19:21] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:21:49 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:21:49 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:21:50 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:21:50 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:21:51 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\paper.py', reloading
2025-06-28 14:21:52 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:21:53 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:21:53 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:21:54 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 14:21:54 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:21:55 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:21:55 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:23:02 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\middleware\\auth.py', reloading
2025-06-28 14:23:02 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:23:03 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:23:03 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:23:17 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 14:23:17 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 14:23:17 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:23:18 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:23:18 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:23:25 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:23:25] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:23:25 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:23:25 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:23:25 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:23:25 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2087, in _generate_backref
    raise sa_exc.ArgumentError(
    ...<4 lines>...
    )
sqlalchemy.exc.ArgumentError: Error creating backref 'operations' on relationship 'Operation.user': property of that name exists on mapper 'Mapper[User(users)]'
2025-06-28 14:23:25 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:23:25] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:25:39 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:25:40 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:25:41 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:25:41 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:26:52 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:26:53 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:26:54 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:26:54 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:27:04 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:27:04] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:27:04 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:27:04 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:27:04 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:27:04 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2087, in _generate_backref
    raise sa_exc.ArgumentError(
    ...<4 lines>...
    )
sqlalchemy.exc.ArgumentError: Error creating backref 'user' on relationship 'User.operations': property of that name exists on mapper 'Mapper[Operation(operations)]'
2025-06-28 14:27:04 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:27:04] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:29:10 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\operation_service.py', reloading
2025-06-28 14:29:10 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:29:12 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:29:12 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:29:37 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\dao\\operation_dao.py', reloading
2025-06-28 14:29:37 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:29:38 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:29:38 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:29:42 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:29:42] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:29:42 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:29:42 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:29:42 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:29:42 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2087, in _generate_backref
    raise sa_exc.ArgumentError(
    ...<4 lines>...
    )
sqlalchemy.exc.ArgumentError: Error creating backref 'user' on relationship 'User.operations': property of that name exists on mapper 'Mapper[Operation(operations)]'
2025-06-28 14:29:42 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:29:42] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:29:43 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:29:43 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:29:43 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:29:43 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4251, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[User(users)]'. Original exception was: Error creating backref 'user' on relationship 'User.operations': property of that name exists on mapper 'Mapper[Operation(operations)]'
2025-06-28 14:29:43 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:29:43] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:31:50 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:31:50 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:31:51 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:31:51 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:31:53 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 14:31:53 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:31:54 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:31:54 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:32:28 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:32:28] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:32:28 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:32:28 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:32:28 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:32:28 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 41, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2087, in _generate_backref
    raise sa_exc.ArgumentError(
    ...<4 lines>...
    )
sqlalchemy.exc.ArgumentError: Error creating backref 'operations' on relationship 'Operation.user': property of that name exists on mapper 'Mapper[User(users)]'
2025-06-28 14:32:28 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:32:28] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:34:16 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 14:34:17 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:34:18 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:34:18 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:34:38 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:34:38 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:34:39 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:34:39 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:38:12 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 14:38:12 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:38:14 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:38:14 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:38:16 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\dao\\operation_dao.py', reloading
2025-06-28 14:38:16 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:38:17 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:38:17 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:38:24 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:38:24] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:38:24 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:38:24 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:38:24 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:38:24 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 42, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2087, in _generate_backref
    raise sa_exc.ArgumentError(
    ...<4 lines>...
    )
sqlalchemy.exc.ArgumentError: Error creating backref 'operation_records' on relationship 'Operation.user': property of that name exists on mapper 'Mapper[User(users)]'
2025-06-28 14:38:24 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:38:24] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:39:42 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:39:42 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:39:43 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:39:43 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:39:55 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 14:39:56 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:39:57 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:39:57 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:40:29 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 14:40:29 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:40:30 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:40:30 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:40:40 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:40:40] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:40:41 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:40:41 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:40:41 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:40:41 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 42, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2087, in _generate_backref
    raise sa_exc.ArgumentError(
    ...<4 lines>...
    )
sqlalchemy.exc.ArgumentError: Error creating backref 'user' on relationship 'User.operation_records': property of that name exists on mapper 'Mapper[Operation(operations)]'
2025-06-28 14:40:41 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:40:41] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:41:41 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:41:41] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:41:41 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:41:41 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:41:41 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:41:41 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 42, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4251, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[User(users)]'. Original exception was: Error creating backref 'user' on relationship 'User.operation_records': property of that name exists on mapper 'Mapper[Operation(operations)]'
2025-06-28 14:41:41 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:41:41] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:42:12 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:42:12] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:42:12 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:42:12 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:42:12 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:42:12 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 42, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4251, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[User(users)]'. Original exception was: Error creating backref 'user' on relationship 'User.operation_records': property of that name exists on mapper 'Mapper[Operation(operations)]'
2025-06-28 14:42:12 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:42:12] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:43:50 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 14:43:50 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:43:51 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:43:51 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:44:09 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:44:09 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:44:10 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:44:10 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:45:52 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\controller\\user_controller.py', reloading
2025-06-28 14:45:52 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:45:53 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:45:53 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:46:01 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:46:01] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 14:46:01 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 14:46:01 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 14:46:01 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 14:46:01 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 42, in login
    user = self.user_dao.get_user_by_identity(email)
  File "D:\2025shixun\papertools\backend\dao\user_dao.py", line 23, in get_user_by_identity
    return User.query.filter(
           ^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ~~~~~~~~~~~~~~~^
        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Python\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "D:\Python\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2087, in _generate_backref
    raise sa_exc.ArgumentError(
    ...<4 lines>...
    )
sqlalchemy.exc.ArgumentError: Error creating backref 'user_operations' on relationship 'Operation.operation_user': property of that name exists on mapper 'Mapper[User(users)]'
2025-06-28 14:46:01 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:46:01] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 14:47:20 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 14:47:21 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:47:22 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:47:22 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:50:54 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 14:50:54 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:50:55 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:50:55 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:51:59 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\controller\\user_controller.py', reloading
2025-06-28 14:51:59 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:52:00 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:52:00 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:52:53 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 14:52:53 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 14:52:53 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:52:54 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:52:54 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:53:06 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 14:53:06 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:53:07 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:53:07 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:53:17 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 14:53:17 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:53:18 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:53:18 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:53:49 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 14:53:50 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:53:51 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:53:51 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:54:07 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:54:07] "OPTIONS /api/user/register HTTP/1.1" 200 -
2025-06-28 14:54:07 - root - INFO - user_controller:131 - 111111111111: admin
2025-06-28 14:54:07 - root - INFO - user_controller:136 - √‹¬Îº”√‹≥…π¶
2025-06-28 14:54:07 - root - INFO - user_service:21 - user_service use rgister
2025-06-28 14:54:07 - dao.user_dao - INFO - user_dao:30 - make new user: admin
2025-06-28 14:54:07 - dao.user_dao - INFO - user_dao:39 -  user 1
2025-06-28 14:54:07 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:54:07] "[35m[1mPOST /api/user/register HTTP/1.1[0m" 500 -
2025-06-28 14:54:10 - root - INFO - user_controller:131 - 111111111111: admin
2025-06-28 14:54:10 - root - INFO - user_controller:136 - √‹¬Îº”√‹≥…π¶
2025-06-28 14:54:10 - root - INFO - user_service:21 - user_service use rgister
2025-06-28 14:54:10 - dao.user_dao - INFO - user_dao:30 - make new user: admin
2025-06-28 14:54:10 - dao.user_dao - INFO - user_dao:39 -  user 1
2025-06-28 14:54:10 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:54:10] "[35m[1mPOST /api/user/register HTTP/1.1[0m" 500 -
2025-06-28 14:56:16 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 14:56:16 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:56:18 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:56:18 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:56:44 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 14:56:44 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:56:45 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:56:45 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:57:02 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 14:57:02 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 14:57:04 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 14:57:04 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 14:57:56 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:57:56] "OPTIONS /api/user/register HTTP/1.1" 200 -
2025-06-28 14:57:56 - root - INFO - user_controller:131 - 111111111111: admin
2025-06-28 14:57:56 - root - INFO - user_controller:136 - √‹¬Îº”√‹≥…π¶
2025-06-28 14:57:56 - root - INFO - user_service:21 - user_service use rgister
2025-06-28 14:57:56 - dao.user_dao - INFO - user_dao:30 - make new user: admin
2025-06-28 14:57:56 - dao.user_dao - INFO - user_dao:39 -  user 1
2025-06-28 14:57:56 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 14:57:56] "[35m[1mPOST /api/user/register HTTP/1.1[0m" 500 -
2025-06-28 15:06:21 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 15:06:21 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 15:06:21 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:06:22 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:06:22 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:07:16 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:07:16] "OPTIONS /api/user/register HTTP/1.1" 200 -
2025-06-28 15:07:16 - root - INFO - user_controller:131 - 111111111111: admin
2025-06-28 15:07:16 - root - INFO - user_controller:136 - √‹¬Îº”√‹≥…π¶
2025-06-28 15:07:16 - root - INFO - user_service:21 - user_service use rgister
2025-06-28 15:07:16 - dao.user_dao - INFO - user_dao:30 - make new user: admin
2025-06-28 15:07:16 - dao.user_dao - INFO - user_dao:39 -  user 1
2025-06-28 15:07:16 - dao.user_dao - INFO - user_dao:50 - new user has been created,waiting for writing
2025-06-28 15:07:16 - dao.user_dao - INFO - user_dao:54 - ”√ªß¥¥Ω®≥…π¶: ID=1, ”√ªß√˚=admin, ” œ‰=2074437070@qq.com
2025-06-28 15:07:16 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:07:16] "[35m[1mPOST /api/user/register HTTP/1.1[0m" 201 -
2025-06-28 15:07:24 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:07:24] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 15:07:24 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 15:07:24 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 15:07:24 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 15:07:24 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 07:07:25
2025-06-28 15:07:24 - root - INFO - user_service:73 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 15:07:24 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 15:07:24 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 257, in login
    current_app.config['123456'],
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: '123456'
2025-06-28 15:07:24 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:07:24] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 15:13:01 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 15:13:01 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:13:02 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:13:02 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:13:22 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\config\\config.py', reloading
2025-06-28 15:13:23 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:13:24 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:13:24 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:14:17 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\controller\\user_controller.py', reloading
2025-06-28 15:14:17 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:14:18 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:14:18 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:14:20 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\middleware\\auth.py', reloading
2025-06-28 15:14:20 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:14:22 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:14:22 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:14:55 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 15:14:55 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:14:56 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:14:56 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:15:00 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:15:00] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 15:15:01 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 15:15:01 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 15:15:01 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 15:15:01 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 07:15:01
2025-06-28 15:15:01 - root - INFO - user_service:73 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 15:15:01 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 15:15:01 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:15:01] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 15:27:39 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 15:27:39 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:29:24 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 15:29:24 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 15:29:24 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:29:25 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:29:25 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:29:42 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 15:29:42 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:29:44 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:29:44 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:30:19 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 15:30:19 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:30:20 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:30:20 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:30:43 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:30:43] "OPTIONS /api/user/register HTTP/1.1" 200 -
2025-06-28 15:30:43 - root - INFO - user_controller:131 - 111111111111: admin
2025-06-28 15:30:43 - root - INFO - user_controller:136 - √‹¬Îº”√‹≥…π¶
2025-06-28 15:30:43 - root - INFO - user_service:21 - user_service use rgister
2025-06-28 15:30:43 - dao.user_dao - INFO - user_dao:30 - make new user: admin
2025-06-28 15:30:43 - dao.user_dao - INFO - user_dao:39 -  user 1
2025-06-28 15:30:43 - dao.user_dao - INFO - user_dao:50 - new user has been created,waiting for writing
2025-06-28 15:30:43 - dao.user_dao - INFO - user_dao:54 - ”√ªß¥¥Ω®≥…π¶: ID=1, ”√ªß√˚=admin, ” œ‰=2074437070@qq.com
2025-06-28 15:30:43 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:30:43] "[35m[1mPOST /api/user/register HTTP/1.1[0m" 201 -
2025-06-28 15:31:06 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:31:06] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 15:31:06 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 15:31:06 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 15:31:06 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 15:31:06 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 07:31:07
2025-06-28 15:31:06 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 68, in login
    Operation.log_operation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        user_id=user.id,
        ^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_name="µ«¬º"
        ^^^^^^^^^^^^^^^^
    )
    ^
TypeError: Operation.log_operation() got an unexpected keyword argument 'file_name'
2025-06-28 15:31:06 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:31:06] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 15:32:10 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 15:32:10 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:32:11 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:32:11 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:32:15 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:32:15] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 15:32:15 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 15:32:15 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 15:32:15 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 15:32:16 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 07:32:16
2025-06-28 15:32:16 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 68, in login
    Operation.log_operation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        user_id=user.id,
        ^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_name="µ«¬º"
        ^^^^^^^^^^^^^^^^
    )
    ^
TypeError: Operation.log_operation() got an unexpected keyword argument 'file_name'
2025-06-28 15:32:16 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:32:16] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 15:32:27 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\app.py', reloading
2025-06-28 15:32:28 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:32:29 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:32:29 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:32:31 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:32:31] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 15:32:31 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 15:32:31 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 15:32:31 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 15:32:31 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 07:32:32
2025-06-28 15:32:31 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 68, in login
    Operation.log_operation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        user_id=user.id,
        ^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_name="µ«¬º"
        ^^^^^^^^^^^^^^^^
    )
    ^
TypeError: Operation.log_operation() got an unexpected keyword argument 'file_name'
2025-06-28 15:32:31 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:32:31] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 15:32:41 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:32:41] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 15:32:41 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 15:32:41 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 15:32:41 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 15:32:41 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 07:32:42
2025-06-28 15:32:41 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 68, in login
    Operation.log_operation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        user_id=user.id,
        ^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_name="µ«¬º"
        ^^^^^^^^^^^^^^^^
    )
    ^
TypeError: Operation.log_operation() got an unexpected keyword argument 'file_name'
2025-06-28 15:32:41 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:32:41] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 15:34:22 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\service\\user_service.py', reloading
2025-06-28 15:34:22 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:34:23 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:34:23 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:34:32 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:34:32] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 15:34:32 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 15:34:32 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 15:34:32 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 15:34:32 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 07:34:33
2025-06-28 15:34:32 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 68, in login
    Operation.log_operation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        user_id=user.id,
        ^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_name="µ«¬º"
        ^^^^^^^^^^^^^^^^
    )
    ^
TypeError: Operation.log_operation() got an unexpected keyword argument 'file_name'
2025-06-28 15:34:32 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:34:32] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 15:36:28 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 15:36:28 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:36:29 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:36:29 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:37:32 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\operation.py', reloading
2025-06-28 15:37:32 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:37:33 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:37:33 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 15:37:35 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:37:35] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 15:37:35 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 15:37:35 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 15:37:35 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 15:37:35 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 07:37:36
2025-06-28 15:37:35 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 15:37:35 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 15:37:35 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 15:37:35] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 15:52:11 - werkzeug - INFO - _internal:97 -  * Detected change in 'D:\\2025shixun\\papertools\\backend\\models\\user.py', reloading
2025-06-28 15:52:11 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 15:52:12 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 15:52:12 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 16:24:11 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 16:24:11 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 16:24:11 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 16:24:12 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 16:24:12 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 16:26:47 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:26:47] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:26:48 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:26:48 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:26:48 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:26:48 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:26:48
2025-06-28 16:26:48 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:26:48 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:26:48 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:26:48] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:27:02 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:27:02] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:27:03 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:27:03 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:27:03 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:27:03 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:27:03
2025-06-28 16:27:03 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:27:03 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:27:03 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:27:03] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:28:23 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:28:23] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:28:23 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:28:23 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:28:23 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:28:23 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:28:23
2025-06-28 16:28:23 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:28:23 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:28:23 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:28:23] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:36:50 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:36:50] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:36:50 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:36:50 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:36:50 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:36:50 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:36:50
2025-06-28 16:36:50 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:36:50 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:36:50 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:36:50] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:36:59 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:36:59] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:36:59 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: admin
2025-06-28 16:36:59 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:36:59 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:36:59 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:37:00
2025-06-28 16:36:59 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:36:59 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:36:59 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:36:59] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:48:01 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:48:01] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:48:01 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:48:01 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:48:01 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:48:01 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:48:02
2025-06-28 16:48:01 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:48:01 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:48:01 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:48:01] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:48:25 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:48:25] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 16:48:31 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:48:31] "[33mGET /operations?page=1&per_page=20 HTTP/1.1[0m" 404 -
2025-06-28 16:48:33 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:48:33] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 16:48:49 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:48:49] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:48:50 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:48:50 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:48:50 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:48:50 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:48:50
2025-06-28 16:48:50 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:48:50 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:48:50 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:48:50] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:52:02 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:52:02] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 16:52:03 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:52:03] "[33mGET /operations?page=1&per_page=20 HTTP/1.1[0m" 404 -
2025-06-28 16:52:04 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:52:04] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 16:52:24 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:52:24] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:52:24 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:52:24 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:52:24 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:52:24 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:52:25
2025-06-28 16:52:24 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:52:24 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:52:24 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:52:24] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:57:08 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:57:08] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:57:08 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:57:08 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:57:08 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:57:08 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:57:09
2025-06-28 16:57:08 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:57:08 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:57:08 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:57:08] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 16:57:44 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:57:44] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 16:57:44 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 16:57:44 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 16:57:44 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 16:57:44 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 08:57:45
2025-06-28 16:57:44 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 16:57:44 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 16:57:44 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 16:57:44] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 17:12:55 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:12:55] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 17:12:55 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 17:12:55 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 17:12:55 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 17:12:55 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 09:12:55
2025-06-28 17:12:55 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 17:12:55 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 17:12:55 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:12:55] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 17:13:51 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:13:51] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 17:15:02 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:15:02] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 17:15:03 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 17:15:03 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 17:15:03 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 17:15:03 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 09:15:03
2025-06-28 17:15:03 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 17:15:03 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 17:15:03 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:15:03] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 17:16:03 - werkzeug - INFO - _internal:97 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-06-28 17:16:03 - werkzeug - INFO - _internal:97 - [33mPress CTRL+C to quit[0m
2025-06-28 17:16:03 - werkzeug - INFO - _internal:97 -  * Restarting with stat
2025-06-28 17:16:04 - werkzeug - WARNING - _internal:97 -  * Debugger is active!
2025-06-28 17:16:04 - werkzeug - INFO - _internal:97 -  * Debugger PIN: 262-340-303
2025-06-28 17:17:00 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:17:00] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 17:17:00 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: 2074437070@qq.com
2025-06-28 17:17:00 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 17:17:00 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 17:17:00 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 09:17:01
2025-06-28 17:17:00 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 17:17:00 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 17:17:00 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:17:00] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 17:20:46 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:20:46] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 17:20:55 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:20:55] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 17:20:56 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:20:56] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 17:20:56 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:20:56] "[33mGET /user/list HTTP/1.1[0m" 404 -
2025-06-28 17:24:24 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:24:24] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 17:24:24 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: admin
2025-06-28 17:24:24 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 17:24:24 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 17:24:24 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 09:24:24
2025-06-28 17:24:24 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 17:24:24 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 17:24:24 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:24:24] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 17:24:34 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:24:34] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 17:24:34 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: asd
2025-06-28 17:24:34 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 17:24:34 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 17:24:34 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 45, in login
    user.updated_at = datetime.now(timezone.utc)
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'updated_at' and no __dict__ for setting new attributes
2025-06-28 17:24:34 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:24:34] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 17:24:36 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: asd
2025-06-28 17:24:36 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 17:24:36 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 17:24:36 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 45, in login
    user.updated_at = datetime.now(timezone.utc)
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'updated_at' and no __dict__ for setting new attributes
2025-06-28 17:24:36 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:24:36] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 17:24:41 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:24:41] "OPTIONS /api/user/login HTTP/1.1" 200 -
2025-06-28 17:24:41 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: admin1
2025-06-28 17:24:41 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 17:24:41 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 17:24:41 - app - ERROR - user_controller:280 - µ«¬ºπ˝≥Ã÷–∑¢…˙“‚Õ‚¥ÌŒÛ
Traceback (most recent call last):
  File "D:\2025shixun\papertools\backend\controller\user_controller.py", line 236, in login
    result = user_service.login(data.get('email'), data.get('password'))
  File "D:\2025shixun\papertools\backend\service\user_service.py", line 45, in login
    user.updated_at = datetime.now(timezone.utc)
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'updated_at' and no __dict__ for setting new attributes
2025-06-28 17:24:41 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:24:41] "[35m[1mPOST /api/user/login HTTP/1.1[0m" 500 -
2025-06-28 17:24:44 - root - INFO - user_controller:227 - ¥¶¿Ì ˝æ›: admin
2025-06-28 17:24:44 - root - INFO - user_controller:228 - ¥¶¿Ì ˝æ›: 123456
2025-06-28 17:24:44 - dao.user_dao - INFO - user_dao:21 - check user
2025-06-28 17:24:44 - root - INFO - user_service:47 - ∏¸–¬◊Ó∫Ûµ«¬º ±º‰: 2025-06-28 09:24:45
2025-06-28 17:24:44 - root - INFO - user_service:74 - µ«¬º≥…π¶ - ”√ªß: admin
2025-06-28 17:24:44 - root - INFO - user_controller:237 - —È÷§√‹¬Îing
2025-06-28 17:24:44 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:24:44] "POST /api/user/login HTTP/1.1" 200 -
2025-06-28 17:25:10 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:25:10] "OPTIONS /api/user/register HTTP/1.1" 200 -
2025-06-28 17:25:10 - root - INFO - user_controller:131 - 111111111111: admin1
2025-06-28 17:25:10 - root - INFO - user_controller:136 - √‹¬Îº”√‹≥…π¶
2025-06-28 17:25:10 - root - INFO - user_service:21 - user_service use rgister
2025-06-28 17:25:10 - dao.user_dao - INFO - user_dao:30 - make new user: admin1
2025-06-28 17:25:10 - dao.user_dao - INFO - user_dao:39 -  user 1
2025-06-28 17:25:10 - dao.user_dao - INFO - user_dao:50 - new user has been created,waiting for writing
2025-06-28 17:25:10 - dao.user_dao - INFO - user_dao:54 - ”√ªß¥¥Ω®≥…π¶: ID=2, ”√ªß√˚=admin1, ” œ‰=lein94255@gmail.com
2025-06-28 17:25:10 - werkzeug - INFO - _internal:97 - 127.0.0.1 - - [28/Jun/2025 17:25:10] "[35m[1mPOST /api/user/register HTTP/1.1[0m" 201 -
